### ISSUE TITLE
Notifications with identical uniqueIds should not result in a new notification

### ISSUE THREAD

**Issue by julianlam** [psychobunny/nodebb-plugin-desktop-notifications#2]
![selection_013](https://f.cloud.github.com/assets/923011/1845548/447f82dc-7591-11e3-9005-b29fe2e95430.png)

Note the above are both pointing to the same topic, but in NodeBB, they are given the same `uniqueId`, `topic:436`. If a new notification alert comes in that has the same `uniqueId` as an already existing notification, trash the existing notification and replace it with the newer one.

**Comment by psychobunny** [comment]
Fixed in core
