### ISSUE TITLE
The notification strip should say the site name instead of nodebb

### ISSUE THREAD

**Issue by smartameer** [psychobunny/nodebb-plugin-desktop-notifications#21]
I think plugin should ask the permission in th name of website which is available in config file, instead of asking in the name of Nodebb.

`Nodebb needs your permission to activate desktop notifications. Click here to activate them.`

**Comment by psychobunny** [comment]
I had forgotten to close this issue, but this was already addressed some time ago:
https://github.com/psychobunny/nodebb-plugin-desktop-notifications/commit/d529668b5cc62e6880075ac0cdd51ee28eeb313a#diff-681b22db1461a74800ed243a7bd28eed

Are you still having this problem?

**Comment by jimmykane** [comment]
Was about to enable the plug-in but I always proactively check for issues. Thanks for the reply. I'll enable it and report back. 

May you have a super day further and thanks again.
