### ISSUE TITLE
New thread notification

### ISSUE THREAD

**Issue by giorgiochiodi** [psychobunny/nodebb-plugin-desktop-notifications#5]
I don't know if there's a notification already in place, since I'm having a bit of problems with my installation's notifications on my local machine.

Anyway, I haven't seen them on nodebb's forum so I guess it's not a feature yet.

It would be handy to have a notification pop up for every new thread in the categories you're following

**Comment by psychobunny** [comment]
Probably should be re-posted in NodeBB's issue tracker
